### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!

### ISSUE THREAD

**Issue by fengwenhua** [fupinglee/CalculateCaptcha_Recognition#1]
`train.py`文件中的`calculat_acc`函数需要加入以下内容：

> 不然会报错：`Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!`

```python 
target = target.to(device=torch.device('cuda:0' if torch.cuda.is_available() else 'cpu'))
```

![image](https://user-images.githubusercontent.com/26518808/156008950-f5d33b3b-e7d0-41f5-8bdf-23c72d0e69d4.png)

`test.py`文件中的`predict`函数需要加入以下内容：

> 不然会报错：`Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

```python
net.to(torch.device('cuda:0' if torch.cuda.is_available() else 'cpu'))
```

![image](https://user-images.githubusercontent.com/26518808/156011563-e4da264f-a236-4b2e-a9e2-5db63e29a521.png)

**Comment by fupinglee** [comment]
感谢指出，将在下次更新时修改
